<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-results  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nunit_schema_2.5.xsd" name="Pester" total="23" errors="0" failures="7" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2013-06-19" time="13:09:07">
	<environment nunit-version="2.5.8.0" clr-version="2.0.50727.1433" os-version="6.1.7600" platform="Microsoft Windows 7 Enterprise |C:\WINDOWS|\Device\Harddisk0\Partition1" cwd="D:\git_root\WordRef\src" machine-name="BGC-PYIN3" user="PYin3" user-domain="DIR" /> <culture-info current-culture="en-US" current-uiculture="en-US" />
	<test-suite type="Powershell" name="AutoUpdate" executed="True" result="Failure" success="False" time="19.1868064" asserts="0"> <results> 		<test-case name="Open Word successful" executed="True" result="Success" success="True" time="5.5513979" asserts="0" /> <test-case name="WordRef-AbsoluteRef:Successful update field" executed="True" result="Success" success="True" time="3.2452759" asserts="0" /> <test-case name="WordRef-AbsoluteRef:Successful update precisely" executed="True" result="Failure" success="False" time="4.0257247" asserts="0"> 	<failure> 		<message>Expected: {WordRef06192013130840}, But was {WordRef03052013105816}</message> 		<stack-trace>at line: 71 in D:\git_root\WordRef\src\WordRef.tests.ps1</stack-trace> 	</failure> </test-case> <test-case name="WordRef-RefInTextBox-AbsolutePath:Successful update field" executed="True" result="Success" success="True" time="2.5900702" asserts="0" /> <test-case name="WordRef-RefInTextBox-AbsolutePath:Successful update field precisely" executed="True" result="Failure" success="False" time="3.7743377" asserts="0"> 	<failure> 		<message>Expected: {WordRef06192013130847}, But was {WordRef03052013105816}</message> 		<stack-trace>at line: 91 in D:\git_root\WordRef\src\WordRef.tests.ps1</stack-trace> 	</failure> </test-case> 	</results> </test-suite> <test-suite type="Powershell" name="UpdateDocContent" executed="True" result="Success" success="True" time="2.2899636" asserts="0"> <results> 		<test-case name="Update file:WordRef-Src.docx in D:\git_root\WordRef\src\WordRef-Src.docx successful precisely" executed="True" result="Success" success="True" time="1.135926" asserts="0" /> <test-case name="Update doc successful" executed="True" result="Success" success="True" time="1.1526022" asserts="0" /> <test-case name="Get actual path of test file WordRef-Src.docx" executed="True" result="Success" success="True" time="0.0014354" asserts="0" /> 	</results> </test-suite> <test-suite type="Powershell" name="Search" executed="True" result="Success" success="True" time="0.0012904" asserts="0"> <results> 		<test-case name="Not implemented" executed="True" result="Success" success="True" time="0.0012904" asserts="0" /> 	</results> </test-suite> <test-suite type="Powershell" name="SetPath" executed="True" result="Failure" success="False" time="4.4246041" asserts="0"> <results> 		<test-case name="SetPath successful" executed="True" result="Success" success="True" time="1.0471884" asserts="0" /> <test-case name="SetPath including Shapes successful" executed="True" result="Success" success="True" time="1.0732576" asserts="0" /> <test-case name="SetPath including Shapes successful precisely" executed="True" result="Failure" success="False" time="2.3041581" asserts="0"> 	<failure> 		<message>Expected: {D:\git_root\WordRef\src\NewRefPath}, But was {System.Management.ManagementBaseObject}</message> 		<stack-trace>at line: 169 in D:\git_root\WordRef\src\WordRef.tests.ps1</stack-trace> 	</failure> </test-case> 	</results> </test-suite> <test-suite type="Powershell" name="GetDocContent" executed="True" result="Success" success="True" time="2.0658958" asserts="0"> <results> 		<test-case name="Get doc content successful" executed="True" result="Success" success="True" time="1.0825435" asserts="0" /> <test-case name="Get doc content in textbox successful" executed="True" result="Success" success="True" time="0.9833523" asserts="0" /> 	</results> </test-suite> <test-suite type="Powershell" name="List" executed="True" result="Failure" success="False" time="3.2948493" asserts="0"> <results> 		<test-case name="List all ref in WordRef-AbsoluteRefMultiItems successful" executed="True" result="Failure" success="False" time="1.1206281" asserts="0"> 	<failure> 		<message>Expected: {4}, But was {6}</message> 		<stack-trace>at line: 207 in D:\git_root\WordRef\src\WordRef.tests.ps1</stack-trace> 	</failure> </test-case> <test-case name="List all ref in WordRef-AbsoluteRefMultiItems showAsFullPath successful" executed="True" result="Failure" success="False" time="1.079291" asserts="0"> 	<failure> 		<message>Expected: {4}, But was {5}</message> 		<stack-trace>at line: 211 in D:\git_root\WordRef\src\WordRef.tests.ps1</stack-trace> 	</failure> </test-case> <test-case name="List all ref in WordRef-AbsoluteRefMultiItems showAsPath successful" executed="True" result="Failure" success="False" time="1.0949302" asserts="0"> 	<failure> 		<message>Expected: {4}, But was {5}</message> 		<stack-trace>at line: 215 in D:\git_root\WordRef\src\WordRef.tests.ps1</stack-trace> 	</failure> </test-case> 	</results> </test-suite> <test-suite type="Powershell" name="Remove" executed="True" result="Success" success="True" time="0.0012918" asserts="0"> <results> 		<test-case name="Not implemented" executed="True" result="Success" success="True" time="0.0012918" asserts="0" /> 	</results> </test-suite> <test-suite type="Powershell" name="Rename" executed="True" result="Failure" success="False" time="4.4162567" asserts="0"> <results> 		<test-case name="Rename ref name all to src3 successful" executed="True" result="Success" success="True" time="1.4805873" asserts="0" /> <test-case name="Rename ref name all to src3 successful precisely" executed="True" result="Failure" success="False" time="2.9356694" asserts="0"> 	<failure> 		<message>Expected: {WordRef-src3.docx}, But was {System.Management.ManagementBaseObject}</message> 		<stack-trace>at line: 237 in D:\git_root\WordRef\src\WordRef.tests.ps1</stack-trace> 	</failure> </test-case> 	</results> </test-suite> <test-suite type="Powershell" name="StopWordProcess" executed="True" result="Success" success="True" time="0.0002029" asserts="0"> <results> 		<test-case name="Clean all word process before running" executed="True" result="Success" success="True" time="0.000103" asserts="0" /> <test-case name="Todo:How to test the confirm" executed="True" result="Success" success="True" time="9.99E-05" asserts="0" /> 	</results> </test-suite> <test-suite type="Powershell" name="StringControl" executed="True" result="Success" success="True" time="0.0013221" asserts="0"> <results> 		<test-case name="Remove Special Character success" executed="True" result="Success" success="True" time="0.0013221" asserts="0" /> 	</results> </test-suite> <test-suite type="Powershell" name="ResetPath" executed="True" result="Success" success="True" time="0" asserts="0"> <results> 		 	</results> </test-suite>
</test-results>
